language: python
python:
  - "2.7"
before_install:
  - pip install codecov
  - pip install mechanize
install:
  - pip install .
  - python RRZE-HPC/kerncraft/get-iaca.sh
before_script:
  - export PATH=$PATH:$PWD/iaca-lin64/bin/
script: 
    - coverage run tests/all_tests.py
    - kerncraft -m examples/machine-files/phinally.yaml examples/kernels/2d-5pt.c -D N 2000 -D M 2000 -p ECM -p ECMCPU -p ECMData -p RooflineIACA -p Roofline
after_success:
  - codecov
